; PlatformIO Project Configuration File
;
;   HMI de captacion de pozos profundos sobre Cheap Yellow Display (ESP32-2432S028R)
;   Pantalla: ILI9341 320x240 (TFT_eSPI) - Tactil: XPT2046 resistivo (bus SPI dedicado)
;   GUI: LVGL 8.4
;
; https://randomnerdtutorials.com/cheap-yellow-display-esp32-2432s028r/

[env:esp32-2432S028R]
platform = espressif32
board = esp32dev
framework = arduino

board_build.partitions = min_spiffs.csv

monitor_speed = 115200
monitor_filters = esp32_exception_decoder
upload_speed = 921600
upload_port = COM10
monitor_port = COM10

lib_deps =
	lvgl/lvgl @ ^8.4.0
	bodmer/TFT_eSPI @ ^2.5.43
	https://github.com/PaulStoffregen/XPT2046_Touchscreen.git
	emelianov/modbus-esp8266 @ ^4.1.0     ; Fase 2: cliente Modbus TCP -> Mapa B (LOGO! 9 / PLC-SIM)
	; --- Fases posteriores ---
	; bblanchon/ArduinoJson @ ^7.0.4
	; knolleary/PubSubClient @ ^2.8

build_flags =
	-D CORE_DEBUG_LEVEL=0
	; ----- LVGL: usar lv_conf.h del proyecto (include/) -----
	-D LV_CONF_INCLUDE_SIMPLE
	-I include
	-I src
	; ----- TFT_eSPI: configuracion CYD (ESP32-2432S028R) por build flags -----
	-D USER_SETUP_LOADED=1
	-D ILI9341_2_DRIVER=1
	-D TFT_WIDTH=240
	-D TFT_HEIGHT=320
	-D TFT_MISO=12
	-D TFT_MOSI=13
	-D TFT_SCLK=14
	-D TFT_CS=15
	-D TFT_DC=2
	-D TFT_RST=-1
	-D TFT_BL=21
	-D TFT_BACKLIGHT_ON=HIGH
	-D LOAD_GLCD
	-D LOAD_FONT2
	-D LOAD_FONT4
	-D LOAD_FONT6
	-D LOAD_FONT7
	-D LOAD_FONT8
	-D LOAD_GFXFF
	-D SMOOTH_FONT
	-D SPI_FREQUENCY=55000000
	-D SPI_READ_FREQUENCY=20000000
	-D SPI_TOUCH_FREQUENCY=2500000
